version: 2

checks: # Configuration of maintainability checks
  similar-code:
    enabled: false
    config:
      threshold: # overriding will affect all languages
  identical-code:
    enabled: false
    config:
      threshold: # overriding will affect all languages

exclude_patterns: # Exclude files and/or directories from analysis
  - .bundle/
  - spec/**/*
  - benchmarks/**/*
  - node_modules/**/*
  - coverage/**/*
