language: node_js
sudo: enabled

node_js:
  - 'node'
  - '10'
  - '8'
  - '6'

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master
  - develop

before_install:
  - mkdir -p build/js
  - sudo apt-get install -y nodejs
  - node --version
  - rm -rf ./node_modules package-lock.json
  - npm install 

install:
  - npm install --save-dev babel-minify uglify-es uglifyjs-webpack-plugin # minify
  - npm install --save-dev babel-cli babel-preset-env # es5 convert
  - npm install --save-dev -g npx
  - npm install --save-dev -g jshint # code quality
  - npm install --save-dev -g istanbul
  - sudo pip install codecov

# command to run tests
script: 
  - echo "jshint src/logni.js ... "
  - jshint --verbose --show-non-errors src/logni.js

  - echo "babel minify src/logni.js ... "
  - ./node_modules/babel-minify/bin/minify.js src/logni.js -o build/js/logni.min.js

  - echo "uglifyjs es6 minify src/logni.js ... "
  - ./node_modules/uglify-es/bin/uglifyjs --verbose --warn src/logni.js

  - echo "convert es6->es5 build/js/lognies5.js ... "
  - npx babel src/logni.js --presets babel-preset-env > build/js/lognies5.js

  - echo "uglifyjs es5 minify src/logni.js ... "
  - ./node_modules/uglifyjs-webpack-plugin/node_modules/uglify-js/bin/uglifyjs build/js/lognies5.js

  - echo "istanbul cover src/logni.js ... "
  - istanbul cover src/logni.js
  - istanbul cover build/js/lognies5.js

  - echo "codecov ... "
  - codecov --token=084bed59-2200-41df-ad02-0117dc01416d

env:
  - CODECOV_TOKEN="084bed59-2200-41df-ad02-0117dc01416d"

after_success:
  - codecov
