language: node_js
sudo: enabled

node_js:
  - 'node'
  - '8'
  - '6'
  - '4'
  - '0.12'
  - '0.10'

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master
  - develop

before_install:
  - mkdir -p build/js
  - sudo apt-get install -y nodejs
  - node --version
  - rm -rf ./node_modules package-lock.json
  - npm install 

install:
  - sudo npm install -g jshint
  - npm install babel-minify

# command to run tests
script: 
  - ./node_modules/babel-minify/bin/minify.js src/logni.js -o build/js/logni.min.js
  - jshint --verbose --show-non-errors src/logni.js
