language: node_js
sudo: enabled

node_js:
	- 8
	- 10
	- 11

branches:
        only:
        - master
        - develop

before_install:
        - sudo npm install -g jshint

# command to run tests
script: jshint --verbose --show-non-errors src/logni.js
