language: node_js
sudo: enabled

node_js:
  - 8
  - 10
  - 11

branches:
  only:
  - master
  - develop

before_install:
  - mkdir -p build/js
  - sudo apt-get install -y nodejs

install:
  - sudo npm install -g jshint
  - sudo npm install babel-minify

# command to run tests
script: 
  - ./node_modules/babel-minify/bin/minify.js src/logni.js -o build/js/logni.min.js
  - jshint --verbose --show-non-errors src/logni.js
