version: "{build}"

# branches to build
branches:
  # whitelist
  only:
    - develop
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 10

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build cache to preserve files/folders between builds
cache:
  - node_modules # local npm modules
  - '%APPDATA%\npm-cache' # npm cache
#  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache

install:
  - md build\js
  - del /f node_modules package-lock.json
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install 
  - npm install --save-dev babel-minify uglify-es
  - set PATH=%USERPROFILE%\;%PATH%
  - npm install jshint

# to run your custom scripts instead of automatic tests
test_script:
  - npm --version
  - cmd: C:\projects\logni-js\node_modules\babel-minify\bin\minify.js src\logni.js -o build\js\logni.min.js
  - cmd: C:\projects\logni-js\node_modules\uglify-es\bin\uglifyjs --verbose --warn src\logni.js
  - cmd: C:\projects\logni-js\node_modules\jshint\bin\jshint --verbose --show-non-errors src\logni.js

notifications:

  # Email
  - provider: Email
    to:
      - erik@brozek.name
    subject: 'Logni.js: Build {{status}}'     # optional
    message: "{{message}}, {{commitId}}, ..." # optional
    on_build_status_changed: true

# Don't actually build.
build: off

# Turn off test scripts
test: off
