version: "{build}"

# branches to build
branches:
  # whitelist
  only:
    - develop
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 10

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build cache to preserve files/folders between builds
cache:
  - node_modules # local npm modules

install:
  - mkdir -p build/js
  - sudo apt-get install -y nodejs
  - node --version
  - rm -rf ./node_modules package-lock.json
  - npm install 
  - npm install babel-minify
  - npm install -g jshint
  - npm install -g istanbul

# to run your custom scripts instead of automatic tests
test_script:
  - echo "minify src/logni.js ... "
  - ./node_modules/babel-minify/bin/minify.js src/logni.js -o build/js/logni.min.js

  - echo "jshint src/logni.js ... "
  - jshint --verbose --show-non-errors src/logni.js

  - echo "istanbul cover src/logni.js ... "
  - istanbul cover src/logni.js

notifications:

  # Email
  - provider: Email
    to:
      - erik@brozek.name
    subject: 'Logni.js: Build {{status}}'     # optional
    message: "{{message}}, {{commitId}}, ..." # optional
    on_build_status_changed: true
